export interface WordEntry {
  word: string;
  hint: string; // riddle-style description
}

export const easyWords: WordEntry[] = [
  // Original words
  { word: 'apple', hint: 'A crunchy red fruit that grows on trees' },
  { word: 'house', hint: 'A place where your family lives' },
  { word: 'happy', hint: 'How you feel when something great happens' },
  { word: 'green', hint: 'The color of grass and leaves' },
  { word: 'smile', hint: 'What your mouth does when you are glad' },
  { word: 'water', hint: 'You drink this when you are thirsty' },
  { word: 'light', hint: 'You turn this on when a room is dark' },
  { word: 'plant', hint: 'It grows in the soil and has leaves' },
  { word: 'music', hint: 'Sounds that you sing or play on instruments' },
  { word: 'cloud', hint: 'A fluffy white shape floating in the sky' },
  { word: 'beach', hint: 'A sandy place next to the ocean' },
  { word: 'tiger', hint: 'A big stripy cat that lives in the jungle' },
  { word: 'dream', hint: 'A story your brain tells you while you sleep' },
  { word: 'grape', hint: 'A tiny round fruit that grows in bunches' },
  { word: 'train', hint: 'It rides on tracks and goes choo choo' },
  { word: 'dance', hint: 'Moving your body to the beat of a song' },
  { word: 'snow', hint: 'Cold white flakes that fall from the sky in winter' },
  { word: 'star', hint: 'A tiny light that twinkles in the night sky' },
  { word: 'cake', hint: 'A sweet treat you eat on your birthday' },
  { word: 'moon', hint: 'The big round thing that glows at night' },
  { word: 'bird', hint: 'An animal with feathers that can fly' },
  { word: 'fish', hint: 'It swims in the water and has fins' },
  { word: 'rain', hint: 'Drops of water that fall from the clouds' },
  { word: 'tree', hint: 'A tall thing with branches and leaves' },
  { word: 'book', hint: 'You open it to read a story' },
  { word: 'frog', hint: 'A small animal that hops and says ribbit' },
  { word: 'king', hint: 'He wears a crown and rules a kingdom' },
  { word: 'jump', hint: 'Push off the ground and fly up into the air' },
  { word: 'leaf', hint: 'A flat green part that grows on a branch' },
  { word: 'bear', hint: 'A big furry animal that loves honey' },
  { word: 'kite', hint: 'You fly this on a string when it is windy' },
  { word: 'nest', hint: 'A cozy home that a bird builds for its eggs' },
  { word: 'boat', hint: 'It floats on water and takes you across a lake' },
  { word: 'lamp', hint: 'A light you put on a table or desk' },
  { word: 'bell', hint: 'You ring it and it makes a ding sound' },
  { word: 'rock', hint: 'A hard lump you find on the ground outside' },
  // New words — Animals
  { word: 'mouse', hint: 'A tiny animal with big ears and a long tail' },
  { word: 'horse', hint: 'A big animal you can ride with a flowing mane' },
  { word: 'sheep', hint: 'A fluffy farm animal that says baa' },
  { word: 'whale', hint: 'The biggest animal in the ocean' },
  { word: 'snake', hint: 'A long animal with no legs that slithers' },
  { word: 'eagle', hint: 'A big bird that soars high in the sky' },
  { word: 'puppy', hint: 'A baby dog that loves to play and lick' },
  { word: 'panda', hint: 'A black and white bear that eats bamboo' },
  { word: 'shark', hint: 'A big fish with sharp teeth in the ocean' },
  { word: 'bunny', hint: 'A small fluffy animal with long ears that hops' },
  { word: 'goose', hint: 'A big white bird that honks loudly' },
  { word: 'camel', hint: 'A desert animal with a hump on its back' },
  { word: 'otter', hint: 'A playful furry animal that swims on its back' },
  { word: 'zebra', hint: 'A horse-like animal with black and white stripes' },
  // New words — Nature & Weather
  { word: 'river', hint: 'A long stream of water that flows to the sea' },
  { word: 'stone', hint: 'A small hard piece of the earth you can hold' },
  { word: 'grass', hint: 'The green stuff that covers the ground outside' },
  { word: 'storm', hint: 'When wind blows hard and rain pours down' },
  { word: 'ocean', hint: 'A huge body of salty water covering the earth' },
  { word: 'flame', hint: 'The hot bright part of a fire' },
  { word: 'frost', hint: 'Thin ice crystals that form on cold mornings' },
  { word: 'pearl', hint: 'A shiny white gem found inside a shell' },
  { word: 'earth', hint: 'The planet we all live on' },
  { word: 'coral', hint: 'Colorful underwater structures where fish hide' },
  // New words — Food & Drink
  { word: 'bread', hint: 'A soft food you use to make sandwiches' },
  { word: 'peach', hint: 'A soft fuzzy fruit that is orange and sweet' },
  { word: 'candy', hint: 'A sugary treat that comes in many flavors' },
  { word: 'honey', hint: 'A sweet golden liquid made by bees' },
  { word: 'pizza', hint: 'A round flat food with cheese and toppings' },
  { word: 'juice', hint: 'A drink made from squeezed fruit' },
  { word: 'melon', hint: 'A big round fruit that is juicy inside' },
  { word: 'berry', hint: 'A small round fruit like a strawberry or blueberry' },
  { word: 'toast', hint: 'Bread that has been heated until it is crispy' },
  { word: 'salad', hint: 'A bowl of fresh veggies mixed together' },
  // New words — Objects & Things
  { word: 'clock', hint: 'It hangs on the wall and tells you the time' },
  { word: 'chair', hint: 'You sit on this at a table or desk' },
  { word: 'crown', hint: 'A golden circle a king or queen wears on their head' },
  { word: 'brush', hint: 'You use this to fix your hair or paint a picture' },
  { word: 'wheel', hint: 'A round thing that spins to help cars move' },
  { word: 'sword', hint: 'A long sharp weapon that knights carry' },
  { word: 'badge', hint: 'A small pin you wear to show you are special' },
  { word: 'truck', hint: 'A big vehicle that carries heavy loads' },
  { word: 'piano', hint: 'A big instrument with black and white keys' },
  { word: 'shelf', hint: 'A flat board on a wall where you put things' },
  { word: 'globe', hint: 'A round ball that shows a map of the whole world' },
  { word: 'flute', hint: 'A long thin instrument you blow across to play' },
  // New words — Actions & Feelings
  { word: 'brave', hint: 'Not scared even when things are frightening' },
  { word: 'laugh', hint: 'The sound you make when something is funny' },
  { word: 'climb', hint: 'Going up something high using your hands and feet' },
  { word: 'paint', hint: 'To make a colorful picture with a brush' },
  { word: 'sleep', hint: 'What you do at night with your eyes closed' },
  { word: 'think', hint: 'Using your brain to figure something out' },
  { word: 'quiet', hint: 'When there is very little sound around you' },
  { word: 'shine', hint: 'To give off a bright light like the sun' },
  { word: 'magic', hint: 'When impossible things happen like in fairy tales' },
  { word: 'silly', hint: 'Being funny and goofy on purpose' },
  // New words — Places & Spaces
  { word: 'tower', hint: 'A tall narrow building that reaches up high' },
  { word: 'cabin', hint: 'A small wooden house in the woods' },
  { word: 'marsh', hint: 'A wet muddy area where tall grass grows' },
  { word: 'space', hint: 'The dark area beyond the sky where stars live' },
  { word: 'trail', hint: 'A narrow path through the woods for walking' },
  { word: 'field', hint: 'A big flat open area of grass or crops' },
  { word: 'cliff', hint: 'A tall steep rock face at the edge of the land' },
  { word: 'igloo', hint: 'A dome-shaped house made of blocks of snow' },
  { word: 'manor', hint: 'A big fancy house where rich people live' },
  { word: 'ridge', hint: 'The long narrow top of a mountain or hill' },
];

export const mediumWords: WordEntry[] = [
  // Original words
  { word: 'bicycle', hint: 'It has two wheels and you pedal to make it go' },
  { word: 'kitchen', hint: 'The room in your home where food is cooked' },
  { word: 'dolphin', hint: 'A smart sea animal that loves to jump out of the water' },
  { word: 'rainbow', hint: 'Colorful stripes that appear in the sky after it rains' },
  { word: 'garden', hint: 'An outdoor space where flowers and veggies grow' },
  { word: 'monkey', hint: 'A playful animal that swings from tree to tree' },
  { word: 'planet', hint: 'A huge round world that goes around a star' },
  { word: 'castle', hint: 'A big stone building where kings and queens live' },
  { word: 'turtle', hint: 'A slow animal that carries its home on its back' },
  { word: 'rocket', hint: 'It blasts off with fire and smoke to reach outer space' },
  { word: 'pirate', hint: 'A sailor who hunts for buried gold and says arrr' },
  { word: 'dragon', hint: 'A flying creature that breathes fire in stories' },
  { word: 'island', hint: 'A piece of land with water all around it' },
  { word: 'forest', hint: 'A big area filled with trees and wild animals' },
  { word: 'puzzle', hint: 'You fit pieces together to make a picture' },
  { word: 'sunset', hint: 'When the sun goes down and the sky turns orange and pink' },
  { word: 'penguin', hint: 'A black and white bird that waddles but cannot fly' },
  { word: 'spider', hint: 'A small creature with eight legs that spins a web' },
  { word: 'trophy', hint: 'A shiny prize you win for being the best' },
  { word: 'wizard', hint: 'A person in stories who uses magic spells' },
  { word: 'parrot', hint: 'A colorful bird that can copy what you say' },
  { word: 'lemon', hint: 'A sour yellow fruit used to make lemonade' },
  { word: 'candle', hint: 'A stick of wax with a flame on top' },
  { word: 'anchor', hint: 'A heavy metal hook that keeps a ship from floating away' },
  { word: 'helmet', hint: 'You wear this on your head to keep your brain safe' },
  { word: 'blanket', hint: 'A soft cover that keeps you warm in bed' },
  { word: 'crystal', hint: 'A shiny clear stone that sparkles in the light' },
  { word: 'feather', hint: 'A soft light thing that falls off a bird' },
  { word: 'compass', hint: 'A tool with a spinning needle that shows you which way is north' },
  { word: 'village', hint: 'A tiny town with just a few houses and shops' },
  { word: 'sandbox', hint: 'A box full of sand where kids like to play and dig' },
  { word: 'cactus', hint: 'A desert plant covered in sharp pointy spikes' },
  { word: 'goblin', hint: 'A small green troublemaker from fairy tales' },
  { word: 'basket', hint: 'A container made of woven strips, great for carrying things' },
  { word: 'muffin', hint: 'A small round cake you might eat for breakfast' },
  { word: 'circus', hint: 'A show with clowns, acrobats, and animals doing tricks' },
  // New words — Animals & Creatures
  { word: 'leopard', hint: 'A big wild cat with spots all over its body' },
  { word: 'hamster', hint: 'A tiny furry pet that runs on a wheel in its cage' },
  { word: 'octopus', hint: 'A sea creature with eight long arms' },
  { word: 'peacock', hint: 'A bird with a huge fan of colorful tail feathers' },
  { word: 'lobster', hint: 'A red sea creature with big claws' },
  { word: 'pelican', hint: 'A bird with a stretchy pouch under its beak' },
  { word: 'cheetah', hint: 'The fastest animal on land with a spotted coat' },
  { word: 'flamingo', hint: 'A tall pink bird that stands on one leg' },
  { word: 'panther', hint: 'A big sleek black cat that prowls through the jungle' },
  { word: 'sparrow', hint: 'A small brown bird you often see in gardens' },
  { word: 'gorilla', hint: 'A huge strong ape that beats its chest' },
  { word: 'buffalo', hint: 'A big shaggy animal with curved horns' },
  { word: 'cricket', hint: 'A small hopping insect that chirps at night' },
  { word: 'catfish', hint: 'A fish with long whiskers near its mouth' },
  // New words — Nature & Science
  { word: 'volcano', hint: 'A mountain that erupts with hot lava and smoke' },
  { word: 'glacier', hint: 'A huge slow-moving river of ice' },
  { word: 'tornado', hint: 'A spinning funnel of wind that destroys things in its path' },
  { word: 'mineral', hint: 'A natural solid substance found in rocks and soil' },
  { word: 'blossom', hint: 'The flower that appears on a tree in spring' },
  { word: 'climate', hint: 'The usual weather a place has over many years' },
  { word: 'eclipse', hint: 'When the moon blocks the sun and the sky goes dark' },
  { word: 'harvest', hint: 'The time when farmers pick their crops from the fields' },
  { word: 'current', hint: 'The flow of water in a river or ocean' },
  { word: 'boulder', hint: 'A very large rock bigger than your head' },
  { word: 'pebble', hint: 'A tiny smooth stone found near rivers or beaches' },
  { word: 'meadow', hint: 'A grassy field full of wildflowers' },
  // New words — Food & Kitchen
  { word: 'pretzel', hint: 'A twisted baked snack that is salty and crunchy' },
  { word: 'pancake', hint: 'A flat round breakfast food you pour syrup on' },
  { word: 'biscuit', hint: 'A small round baked bread that is soft inside' },
  { word: 'noodle', hint: 'A long thin strip of food you slurp up in soup' },
  { word: 'waffle', hint: 'A breakfast food with little square holes on top' },
  { word: 'coconut', hint: 'A big brown hairy fruit with white inside and milk' },
  { word: 'popcorn', hint: 'Puffed corn kernels you eat at the movies' },
  { word: 'custard', hint: 'A creamy yellow dessert made with eggs and milk' },
  { word: 'ginger', hint: 'A spicy root used in cooking and baking' },
  { word: 'cherry', hint: 'A small round red fruit with a pit inside' },
  // New words — Objects & Adventures
  { word: 'lantern', hint: 'A lamp you carry to light your way in the dark' },
  { word: 'catapult', hint: 'A machine that flings big rocks through the air' },
  { word: 'dungeon', hint: 'A dark underground room in a castle' },
  { word: 'chalice', hint: 'A fancy golden cup used by kings in old times' },
  { word: 'scepter', hint: 'A special rod carried by a king or queen' },
  { word: 'chariot', hint: 'A two-wheeled cart pulled by horses in ancient times' },
  { word: 'trinket', hint: 'A small pretty object like a charm or decoration' },
  { word: 'pottery', hint: 'Bowls and pots made from clay and baked in an oven' },
  { word: 'curtain', hint: 'Fabric that hangs over a window to block the light' },
  { word: 'chimney', hint: 'The tall tube on a roof where smoke goes out' },
  // New words — People & Occupations
  { word: 'captain', hint: 'The person who is in charge of a ship or team' },
  { word: 'soldier', hint: 'A person who wears a uniform and protects their country' },
  { word: 'dentist', hint: 'A doctor who takes care of your teeth' },
  { word: 'teacher', hint: 'The person at school who helps you learn new things' },
  { word: 'painter', hint: 'An artist who makes pictures with paint and brushes' },
  { word: 'farmer', hint: 'A person who grows food and takes care of farm animals' },
  // New words — Fun & Play
  { word: 'costume', hint: 'Special clothes you wear to dress up as someone else' },
  { word: 'balloon', hint: 'A rubber bag you blow up with air for parties' },
  { word: 'juggler', hint: 'A person who throws and catches many balls at once' },
  { word: 'puppet', hint: 'A toy figure you move with your hands or strings' },
  { word: 'quarter', hint: 'A coin worth twenty-five cents' },
  { word: 'pilgrim', hint: 'A traveler on a long journey to a special place' },
  { word: 'garland', hint: 'A string of flowers or leaves used as decoration' },
  { word: 'journey', hint: 'A long trip from one place to another' },
  { word: 'mystery', hint: 'Something strange that is hard to explain or solve' },
  { word: 'kingdom', hint: 'A land ruled by a king or queen' },
  { word: 'monster', hint: 'A scary creature from stories with big teeth and claws' },
  { word: 'mermaid', hint: 'A magical being that is half person and half fish' },
];

export const hardWords: WordEntry[] = [
  // Original words
  { word: 'adventure', hint: 'An exciting journey to somewhere new and unknown' },
  { word: 'beautiful', hint: 'A word that means really, really pretty' },
  { word: 'chocolate', hint: 'A sweet brown treat made from cocoa beans' },
  { word: 'dinosaur', hint: 'A giant reptile that lived millions of years ago' },
  { word: 'wonderful', hint: 'Another way of saying something is really amazing' },
  { word: 'butterfly', hint: 'An insect with big colorful wings that used to be a caterpillar' },
  { word: 'dangerous', hint: 'A word that means something could hurt you' },
  { word: 'education', hint: 'Everything you learn at school and from books' },
  { word: 'invisible', hint: 'When something is there but you cannot see it at all' },
  { word: 'jellyfish', hint: 'A squishy see-through sea creature that can sting you' },
  { word: 'knowledge', hint: 'All the facts and things you have learned' },
  { word: 'landscape', hint: 'A wide view of nature like hills, rivers, and fields' },
  { word: 'moonlight', hint: 'The soft glow the moon makes at night' },
  { word: 'nightmare', hint: 'A scary dream that wakes you up at night' },
  { word: 'pineapple', hint: 'A spiky tropical fruit that is sweet and yellow inside' },
  { word: 'quicksand', hint: 'Wet sandy ground that sucks things down into it' },
  { word: 'satellite', hint: 'A machine that floats in space and sends signals to Earth' },
  { word: 'treasure', hint: 'Gold, jewels, and riches hidden in a secret place' },
  { word: 'telescope', hint: 'A long tube you look through to see faraway stars' },
  { word: 'umbrella', hint: 'You hold this over your head to stay dry when it rains' },
  { word: 'different', hint: 'Not the same as something else' },
  { word: 'fireworks', hint: 'Loud colorful explosions in the sky on special nights' },
  { word: 'happiness', hint: 'The warm feeling inside when everything feels just right' },
  { word: 'lightning', hint: 'A bright flash of electricity that cracks across the sky' },
  { word: 'mountains', hint: 'Huge rocky peaks that reach up into the clouds' },
  { word: 'orchestra', hint: 'A big group of people playing instruments together on stage' },
  { word: 'parachute', hint: 'A big cloth that opens in the air to help you float down slowly' },
  { word: 'surprised', hint: 'How you feel when something happens that you did not expect' },
  { word: 'vegetable', hint: 'A healthy food that grows in a garden, like carrots or peas' },
  { word: 'waterfall', hint: 'A river that drops off a cliff and crashes into a pool below' },
  { word: 'crocodile', hint: 'A big scaly reptile with a long snout and lots of sharp teeth' },
  { word: 'astronaut', hint: 'A brave person who travels to space in a rocket' },
  { word: 'detective', hint: 'Someone who solves mysteries by looking for clues' },
  { word: 'kangaroo', hint: 'An Australian animal that hops and carries babies in a pouch' },
  { word: 'snowflake', hint: 'A tiny ice crystal with a one-of-a-kind shape' },
  { word: 'trampoline', hint: 'A bouncy surface you jump really high on' },
  // New words — Science & Discovery
  { word: 'discovery', hint: 'Finding something that nobody knew about before' },
  { word: 'electricity', hint: 'The energy that powers lights and devices in your home' },
  { word: 'atmosphere', hint: 'The blanket of air that wraps around the whole Earth' },
  { word: 'experiment', hint: 'A test you do to find out if an idea is true' },
  { word: 'microscope', hint: 'A tool that makes tiny things look much bigger' },
  { word: 'thermometer', hint: 'A tool that measures how hot or cold something is' },
  { word: 'hibernate', hint: 'When animals sleep through the whole winter' },
  { word: 'submarine', hint: 'A special boat that can travel underwater' },
  { word: 'avalanche', hint: 'A huge rush of snow sliding down a mountain' },
  { word: 'continent', hint: 'One of the seven big pieces of land on Earth' },
  { word: 'ecosystem', hint: 'All the living things in an area working together' },
  { word: 'evolution', hint: 'How living things slowly change over millions of years' },
  { word: 'magnetism', hint: 'The invisible force that makes magnets stick together' },
  { word: 'migration', hint: 'When animals travel far away to find warmer weather' },
  // New words — Animals & Nature
  { word: 'chameleon', hint: 'A lizard that can change its color to match what is around it' },
  { word: 'porcupine', hint: 'A small animal covered in sharp pointy quills' },
  { word: 'alligator', hint: 'A big reptile with a wide snout that lives in swamps' },
  { word: 'armadillo', hint: 'A small animal with a hard shell like a suit of armor' },
  { word: 'caterpillar', hint: 'A fuzzy crawling bug that will become a butterfly' },
  { word: 'dragonfly', hint: 'A flying insect with long thin wings that hovers over ponds' },
  { word: 'nightingale', hint: 'A small brown bird famous for its beautiful singing at night' },
  { word: 'hedgehog', hint: 'A small round animal covered in tiny spines' },
  { word: 'starfish', hint: 'A sea creature shaped like a star with five arms' },
  { word: 'woodpecker', hint: 'A bird that pecks holes in trees with its beak' },
  { word: 'centipede', hint: 'A long skinny bug with lots and lots of legs' },
  { word: 'orangutan', hint: 'A big red-haired ape that lives in trees in the jungle' },
  // New words — Fantasy & Mythology
  { word: 'enchanted', hint: 'Made magical by a spell or charm' },
  { word: 'labyrinth', hint: 'A twisty winding maze that is hard to escape from' },
  { word: 'legendary', hint: 'So famous that people tell stories about it for years' },
  { word: 'sorcerer', hint: 'A powerful person who uses dark magic in stories' },
  { word: 'mythical', hint: 'Something from old legends that may not be real' },
  { word: 'mysterious', hint: 'Strange and hard to understand or explain' },
  { word: 'companion', hint: 'A friend who goes with you on a journey' },
  { word: 'forbidden', hint: 'Something you are not allowed to do or touch' },
  { word: 'guardian', hint: 'A protector who watches over someone or something special' },
  { word: 'imaginary', hint: 'Something that only exists in your mind and not in real life' },
  // New words — Places & Geography
  { word: 'peninsula', hint: 'A piece of land that sticks out and is surrounded by water on three sides' },
  { word: 'rainforest', hint: 'A thick jungle that gets lots and lots of rain' },
  { word: 'wilderness', hint: 'A wild natural area where no people live' },
  { word: 'shipwreck', hint: 'A boat that crashed and sank to the bottom of the sea' },
  { word: 'cathedral', hint: 'A very big and beautiful church with tall towers' },
  { word: 'colosseum', hint: 'A huge ancient arena where Romans watched games' },
  { word: 'monastery', hint: 'A building where monks live, pray, and work together' },
  { word: 'reservoir', hint: 'A big lake made by people to store drinking water' },
  // New words — Emotions & Qualities
  { word: 'courageous', hint: 'Being very brave even when you are scared' },
  { word: 'determined', hint: 'Not giving up no matter how hard something gets' },
  { word: 'brilliant', hint: 'Extremely smart or shining very brightly' },
  { word: 'excellent', hint: 'So good that it could not be much better' },
  { word: 'fantastic', hint: 'Amazingly great and hard to believe' },
  { word: 'generous', hint: 'Someone who loves to share and give to others' },
  { word: 'obedient', hint: 'Following the rules and doing what you are told' },
  { word: 'confident', hint: 'Believing in yourself and not being afraid to try' },
  { word: 'delightful', hint: 'Something that makes you feel really happy and pleased' },
  { word: 'important', hint: 'Something that matters a lot and should not be ignored' },
  // New words — Adventures & Actions
  { word: 'celebrate', hint: 'Having a party or doing something fun for a special reason' },
  { word: 'disappear', hint: 'To go away so no one can see you anymore' },
  { word: 'carpenter', hint: 'A person who builds things out of wood' },
  { word: 'navigator', hint: 'The person who reads maps and plans which way to go' },
  { word: 'professor', hint: 'A teacher at a college who knows a lot about one subject' },
  { word: 'passenger', hint: 'A person riding in a car, bus, or plane but not driving' },
  { word: 'volunteer', hint: 'Someone who helps out without being paid' },
  { word: 'whirlpool', hint: 'Water that spins around and around in a circle really fast' },
  { word: 'cartwheel', hint: 'A sideways flip where your hands and feet take turns on the ground' },
  { word: 'wrestling', hint: 'A sport where two people try to pin each other down' },
  { word: 'xylophone', hint: 'A musical instrument with colorful bars you hit with mallets' },
  { word: 'dandelion', hint: 'A yellow flower that turns into a fluffy white puff you can blow' },
  { word: 'gymnasium', hint: 'A big room or building where people exercise and play sports' },
  { word: 'binoculars', hint: 'Two connected tubes you look through to see far away things up close' },
];

export type Difficulty = 'easy' | 'medium' | 'hard';

export const wordsByDifficulty: Record<Difficulty, WordEntry[]> = {
  easy: easyWords,
  medium: mediumWords,
  hard: hardWords,
};

export const distractorLetters = 'abcdefghijklmnopqrstuvwxyz';

export function getDistractorCount(difficulty: Difficulty): number {
  switch (difficulty) {
    case 'easy': return 2;
    case 'medium': return 3;
    case 'hard': return 4;
  }
}
